export type HeadlineKind = 'booked' | 'rejected' | 'exposed' | 'tierUp' | 'overdraft' | 'movedHome' | 'creativeBurnout';

/** Placeholders: {who} (e.g. "Midwest Transplant"), {title} (opportunity title), {tier}, {pay} (e.g. "$1,875"), {medium} ("film" | "TV" | "music"). */
export const HEADLINES: Record<HeadlineKind, readonly string[]> = {
  booked: [
    '{who} Books "{title}"; Agent Takes Full Credit',
    '{who} Lands "{title}" for {pay}, Immediately Buys Oat Milk in Bulk',
    'EXCLUSIVE: {who} Attached to "{title}," Sources Say "Sure, Why Not"',
    '{who} Nabs "{title}"; Rivals Cite "Luck," "Lighting"',
    '{medium} Insiders Buzz as {who} Signs On to "{title}" ({pay})',
    'Deal Alert: {who} Closes "{title}" at {pay}, Calls Mom',
    '{who} Cast in "{title}"; Headshot Finally Earns Its Keep',
    'Rising {medium} Name {who} Locks "{title}," Ghosts Group Chat',
  ],
  rejected: [
    '{who} Passed On for "{title}"; Producers "Went Another Direction"',
    '"{title}" Goes With Someone Taller, {who} Reports',
    '{who} Told They Were "Great, Just Not Right" for "{title}"',
    'Casting Loved {who}, Hired Their Cousin',
    '{who} Not Moving Forward on "{title}"; Remains Moving Forward Spiritually',
    '"{title}" Fills Slot Before {who} Finds Parking',
    '{who} Rejection Email Opens With "Hope You\'re Well!"',
  ],
  exposed: [
    'Industry Sniffs Out {who} on "{title}"; Reel Was Mostly B-Roll',
    '{who} Out of Depth on "{title}," Crew Starts Group Chat About It',
    'Tier {tier} Proved a Stretch: {who} Bluffed Through "{title}"',
    '{who} Exposed on "{title}"; Résumé "Embellished," Say Sources',
    '"{title}" Set Sources: {who} Called Action on the Wrong Camera',
    '{medium} World Raises an Eyebrow at {who} After "{title}"',
    '{who} Asked "Have You Done This Before?" on "{title}." Had Not.',
  ],
  tierUp: [
    '{who} Climbs to Tier {tier}; Starts Saying "My Team"',
    'Tier {tier} Unlocked: {who} Now Gets Returned Emails, Sometimes',
    '{who} Hits Tier {tier}, Upgrades From Folding Chair to Director\'s Chair',
    'Heat Index: {who} Is Tier {tier} and Suddenly Everyone\'s Old Friend',
    '{who} Rises to Tier {tier}; Former Roommates Claim "Discovered Them"',
    'The Trades Power Ranking: {who} Enters Tier {tier} in {medium}',
    '{who} Reaches Tier {tier}; Begins Taking Meetings "Just to Chat"',
  ],
  overdraft: [
    '{who} Account Dips Into the Red; Bank Sends "Gentle" Reminder',
    'Box Office Bomb: {who} Checking Account Opens at -$0',
    '{who} Enters Overdraft, Pivots to "Living Off Craft Services"',
    'Bank Greenlights Overdraft Fee for {who}, Plans Sequel',
    '{who} Declined at Coffee Shop; Barista Offers Exposure Instead',
    'Fiscal Thriller: {who} Has Days to Find Rent or Face Ending',
  ],
  movedHome: [
    '{who} Exits LA, Cites "Creative Differences" With Rent',
    '{who} Departs Hollywood to "Pursue Other Projects" (Parents\' Basement)',
    'Final Cut: {who} Wraps LA Run, Hometown Paper Runs Feature',
    '{who} Leaves LA; Plans Community Theater Comeback Tour',
    'Series Cancelled: {who} Moves Home After One Season',
    '{who} Says Goodbye to LA, Keeps the Headshots "Just in Case"',
    '{who} Relocates Home, Tells Everyone It\'s a "Sabbatical"',
  ],
  creativeBurnout: [
    '{who} Hits Creative Wall; Wall Requests Producer Credit',
    'Sources: {who} Has Stared at Blank Page for Three Days',
    '{who} Takes Indefinite Hiatus From Having Ideas',
    '{who} Muse Reportedly Exits for "Bigger Opportunity"',
    '{who} Spark Runs Dry; Tells Friends They\'re "Recharging"',
    'Creative Drought: {who} Reorganizes Spice Rack Instead of Writing',
  ],
};

export const NPC_HEADLINES: readonly string[] = [
  'Wonder Bros Greenlights Sequel to Film Not Yet Released',
  'Streamflix Cancels Hit Show Mid-Episode, Cites "Data"',
  'Paramountain Announces Cinematic Universe for Board Games',
  'Hulo Renews "Cul-de-Sac Cops" for Seasons 9 Through 14',
  'B25 Horror Film About a Haunted Lamp Earns 12-Minute Ovation',
  'Actor Dax Vantablack Gains 40 Lbs of Gravitas for Biopic',
  'Starlet Meadow Q. Sterling Takes "Break From Being Seen," Is Seen',
  'Indie Darling Pip Harrowgate Signs Three-Picture Superhero Deal',
  'Showrunner Glenda Moss Fires Self, Rehires Self at Higher Rate',
  'Velvet Mixtape Records Signs Band That Is Just Two Synths',
  'The Lukewarm Tapes Announce Farewell Tour, Fifth This Decade',
  'DJ Supreme Leftovers Drops Album Exclusively on Cassette',
  'Bedroom-Pop Act Soft Tuesday Leaves Bedroom for First Time',
  'Wonder Bros Merges With Itself, Lays Off Logo',
  'Streamflix Raises Prices, Adds Fewer Shows "for Focus"',
  'Prestige Drama "Long Pause" Wins Award for Most Silence',
  'Studio Exec Brock Fairweather Promoted After Flop "Built Character"',
  'Director Ingrid Vole Demands Real Rain, Gets It, Regrets It',
  'Rapper Lil Overtime Announces Podcast About His Other Podcast',
  'Hulo Teen Vampire Drama Casts 34-Year-Olds as Freshmen',
  'Paramountain+ Launches Channel Showing Only Paramountain+ Ads',
  'Band Neon Parish Sells Out The Whiskey Wobble Before Forming',
  'Composer Ludo Greaves Scores Film Using Only Kazoo, Wins Prize',
  'Remake of Remake Tests Well With People Who Saw Neither',
  'Writers\' Room Reaches Consensus; Studio Investigates',
  'Sundown Fest Darling "Sad Lake" Acquired for Undisclosed Hug',
  'Pop Star Kandi Equinox Releases Album, Perfume, and Apology',
  'Studio Announces Original Film; Shareholders Request Explanation',
  'Actor Rory Penhallow Does Own Stunts, Own Catering, Own Notes',
  '"Hospital Hospital" Introduces Doctor Who Is Also a Lawyer',
  'Label Exec Says Next Big Thing Is "Vibes, But Monetized"',
  'Garage Band The Sublets Evicted From Garage, Tour Anyway',
  'Streaming Giant Hulo Announces Hulo Max Plus Ultra',
  'Producer Tamsin Okafor-Bright Credited on 40 Films This Year',
  'Night Shift Coffee Commercial Wins More Awards Than Feature Slate',
  'Wonder Bros Reboots Franchise That Ended Last Tuesday',
  'Indie Folk Trio Willow & Wren & Wren Adds Third Wren',
  'Superhero Film Delayed to Allow Time for Superhero to Exist',
  'Late-Night Host Chip Danforth Signs Off, Then On, Then Off',
  'Director\'s Cut of Indie Film Runs Seven Hours, Critics Thrilled',
  'B25 Signs Deal to Make Movies "Exactly Like Last Year\'s"',
  'Synthwave Duo Laser Tuxedo Wins Award for Best Sunglasses',
  'Sitcom "Roommates, Ugh" Renewed Despite Everyone Moving Out',
  'Studio Hires AI Consultant, Consultant Hires Human Writer',
];
